# Generated by Django 5.1.1 on 2024-09-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_exerciseresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codinglesson',
            name='difficulty',
            field=models.CharField(max_length=30),
        ),
    ]
