# Generated by Django 5.1.1 on 2024-09-22 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_codinglesson_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='codinglesson',
            name='common_questions',
            field=models.JSONField(blank=True, default=dict, help_text='Frequently asked questions by students.'),
        ),
        migrations.AddField(
            model_name='codinglesson',
            name='feedback_summary',
            field=models.TextField(blank=True, help_text='Summary of student feedback and interactions.', null=True),
        ),
        migrations.AddField(
            model_name='codinglesson',
            name='lecture_goals',
            field=models.TextField(blank=True, help_text='Goals extracted from the lecture PDF.', null=True),
        ),
        migrations.AddField(
            model_name='codinglesson',
            name='lecture_topics',
            field=models.JSONField(blank=True, default=list, help_text='List of topics covered in the lecture.'),
        ),
        migrations.AddField(
            model_name='codinglesson',
            name='struggle_topics',
            field=models.JSONField(blank=True, default=dict, help_text='Topics where students commonly struggle.'),
        ),
        migrations.AddField(
            model_name='codinglesson',
            name='topic_tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags related to the lecture topics.'),
        ),
        migrations.AddField(
            model_name='codinglesson',
            name='total_interactions',
            field=models.PositiveIntegerField(default=0, help_text='Total number of student interactions with this lesson.'),
        ),
        migrations.AlterField(
            model_name='codingexercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the exercise was created.'),
        ),
        migrations.AlterField(
            model_name='codingexercise',
            name='hints',
            field=models.TextField(blank=True, help_text='Hints to assist the student in solving the exercise.', null=True),
        ),
        migrations.AlterField(
            model_name='codingexercise',
            name='lesson',
            field=models.ForeignKey(help_text='The lesson this exercise belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='content.codinglesson'),
        ),
        migrations.AlterField(
            model_name='codingexercise',
            name='prompt',
            field=models.TextField(help_text='The exercise prompt presented to the student.'),
        ),
        migrations.AlterField(
            model_name='codingexercise',
            name='solution_code',
            field=models.TextField(blank=True, help_text='Solution code for the exercise.', null=True),
        ),
        migrations.AlterField(
            model_name='codingexercise',
            name='starter_code',
            field=models.TextField(blank=True, help_text='Starter code provided to the student.', null=True),
        ),
        migrations.AlterField(
            model_name='codinglesson',
            name='chroma_document_id',
            field=models.CharField(help_text='Path or identifier linking to the Chroma document (e.g., PDF file).', max_length=255),
        ),
        migrations.AlterField(
            model_name='codinglesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the lesson was created.'),
        ),
        migrations.AlterField(
            model_name='codinglesson',
            name='description',
            field=models.TextField(help_text='Detailed description of the lesson.'),
        ),
        migrations.AlterField(
            model_name='codinglesson',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], help_text='Difficulty level of the lesson.', max_length=20),
        ),
        migrations.AlterField(
            model_name='codinglesson',
            name='title',
            field=models.CharField(help_text='Title of the lesson.', max_length=255),
        ),
        migrations.CreateModel(
            name='CommonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The frequently asked question.')),
                ('frequency', models.PositiveIntegerField(default=0, help_text='How often the question was asked.')),
                ('lesson', models.ForeignKey(help_text='The lesson associated with this common question.', on_delete=django.db.models.deletion.CASCADE, related_name='common_questions_set', to='content.codinglesson')),
            ],
        ),
        migrations.CreateModel(
            name='StruggleAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='The topic where students struggle.', max_length=255)),
                ('frequency', models.PositiveIntegerField(default=0, help_text='How often students struggled with this topic.')),
                ('lesson', models.ForeignKey(help_text='The lesson associated with this struggle topic.', on_delete=django.db.models.deletion.CASCADE, related_name='struggle_analyses', to='content.codinglesson')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The question asked by the student.')),
                ('response', models.TextField(help_text="The LLM's response to the student's question.")),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the interaction occurred.')),
                ('helpful', models.BooleanField(default=True, help_text='Indicates if the student found the response helpful.')),
                ('exercise', models.ForeignKey(help_text='The exercise associated with this interaction.', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='content.codingexercise')),
                ('lesson', models.ForeignKey(help_text='The lesson associated with this interaction.', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='content.codinglesson')),
            ],
        ),
        migrations.DeleteModel(
            name='ExerciseResponse',
        ),
    ]
